#!/usr/bin/env bash
###############################################################################
# azure-lab-creds.sh
#
# Azure lab credentials refresh from a shared file that rotates every ~1 hour.
#
# The lab drops fresh service-principal credentials into a file. This script:
#   1. Locates that file (ALZ_AZURE_CREDS_FILE or a list of default paths).
#   2. Parses it (JSON from `az ad sp create-for-rbac`, or a KEY=VALUE .env).
#   3. Runs `az login --service-principal` so the Azure CLI token cache is warm.
#      Terraform's azurerm provider falls back to Azure CLI auth automatically,
#      so no ARM_* env propagation into Claude's shell is required.
#   4. Also writes a sourceable env file ($STATE_DIR/azure.env, mode 600) with
#      ARM_* / AZURE_* exports for anyone who wants `source` it.
#   5. Records the login time so callers can cheaply check freshness.
#
# Usage:
#   ./azure-lab-creds.sh            # refresh if stale (>50 min) or logged out
#   ./azure-lab-creds.sh --force    # always re-login
#   ./azure-lab-creds.sh --check    # exit 0 if fresh, 1 if a refresh is needed
#   source ./azure-lab-creds.sh --export   # refresh AND export ARM_* into shell
#
# Configure the source file (pick one):
#   export ALZ_AZURE_CREDS_FILE=/mnt/c/Users/sound/azure-lab-creds.json
#   ...or drop the file at one of the default paths below.
###############################################################################
set -uo pipefail

STATE_DIR="${ALZ_STATE_DIR:-$HOME/.claude/alz}"
mkdir -p "$STATE_DIR" 2>/dev/null || true
ENV_OUT="$STATE_DIR/azure.env"
STAMP="$STATE_DIR/.azure-lastlogin"
MAX_AGE_SECONDS="${ALZ_CREDS_MAX_AGE:-3000}"   # 50 min — refresh before the hourly rotation

log() { printf '[azure-lab-creds] %s\n' "$*" >&2; }

# --- locate the shared credentials file --------------------------------------
find_creds_file() {
  local candidates=(
    "${ALZ_AZURE_CREDS_FILE:-}"
    "$HOME/.azure-lab/creds.json"
    "$HOME/.azure-lab/creds.env"
    "$HOME/azure-lab-creds.json"
    "$HOME/azure-lab-creds.env"
    "$HOME/azure-creds.json"
    "/mnt/c/Users/sound/azure-lab-creds.json"
    "/mnt/c/Users/sound/Downloads/azure-lab-creds.json"
  )
  local f
  for f in "${candidates[@]}"; do
    [ -n "$f" ] && [ -f "$f" ] && { printf '%s' "$f"; return 0; }
  done
  return 1
}

# --- parse creds file into CLIENT_ID/SECRET/TENANT/SUBSCRIPTION --------------
parse_creds() {
  local file="$1"
  CLIENT_ID="" CLIENT_SECRET="" TENANT_ID="" SUBSCRIPTION_ID=""

  if head -c 64 "$file" | grep -q '{'; then
    # JSON — support az-sp-create-for-rbac and generic key styles.
    CLIENT_ID="$(jq -r '.appId // .clientId // .client_id // .ARM_CLIENT_ID // empty' "$file")"
    CLIENT_SECRET="$(jq -r '.password // .clientSecret // .client_secret // .ARM_CLIENT_SECRET // empty' "$file")"
    TENANT_ID="$(jq -r '.tenant // .tenantId // .tenant_id // .ARM_TENANT_ID // empty' "$file")"
    SUBSCRIPTION_ID="$(jq -r '.subscription // .subscriptionId // .subscription_id // .ARM_SUBSCRIPTION_ID // empty' "$file")"
  else
    # dotenv KEY=VALUE — read known keys without executing the file.
    local k v
    while IFS='=' read -r k v; do
      k="$(printf '%s' "$k" | tr -d ' \t' )"
      v="$(printf '%s' "$v" | sed -e 's/^["'\'' ]*//' -e 's/["'\'' ]*$//')"
      case "$k" in
        ARM_CLIENT_ID|AZURE_CLIENT_ID|clientId)         CLIENT_ID="$v" ;;
        ARM_CLIENT_SECRET|AZURE_CLIENT_SECRET|clientSecret) CLIENT_SECRET="$v" ;;
        ARM_TENANT_ID|AZURE_TENANT_ID|tenantId)         TENANT_ID="$v" ;;
        ARM_SUBSCRIPTION_ID|AZURE_SUBSCRIPTION_ID|subscriptionId) SUBSCRIPTION_ID="$v" ;;
      esac
    done < <(grep -E '^[[:space:]]*[A-Za-z_]+[[:space:]]*=' "$file")
  fi

  [ -n "$CLIENT_ID" ] && [ -n "$CLIENT_SECRET" ] && [ -n "$TENANT_ID" ]
}

is_fresh() {
  az account show >/dev/null 2>&1 || return 1
  [ -f "$STAMP" ] || return 1
  local last now; last="$(cat "$STAMP" 2>/dev/null || echo 0)"; now="$(date +%s)"
  [ $(( now - last )) -lt "$MAX_AGE_SECONDS" ]
}

do_login() {
  local file; file="$(find_creds_file)" || {
    log "no credentials file found. Set ALZ_AZURE_CREDS_FILE to your lab creds file."
    return 3
  }
  parse_creds "$file" || { log "could not parse client_id/secret/tenant from $file"; return 4; }

  log "logging in as SP ${CLIENT_ID:0:8}… (source: $file)"
  if ! az login --service-principal \
        --username "$CLIENT_ID" --password "$CLIENT_SECRET" --tenant "$TENANT_ID" \
        --only-show-errors >/dev/null 2>&1; then
    log "az login failed — creds may be expired; check the shared file."
    return 5
  fi
  [ -n "$SUBSCRIPTION_ID" ] && az account set --subscription "$SUBSCRIPTION_ID" --only-show-errors 2>/dev/null || true
  SUBSCRIPTION_ID="${SUBSCRIPTION_ID:-$(az account show --query id -o tsv 2>/dev/null)}"

  umask 077
  cat >"$ENV_OUT" <<EOF
# Auto-generated by azure-lab-creds.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
export ARM_CLIENT_ID="$CLIENT_ID"
export ARM_CLIENT_SECRET="$CLIENT_SECRET"
export ARM_TENANT_ID="$TENANT_ID"
export ARM_SUBSCRIPTION_ID="$SUBSCRIPTION_ID"
export AZURE_CLIENT_ID="$CLIENT_ID"
export AZURE_TENANT_ID="$TENANT_ID"
export AZURE_SUBSCRIPTION_ID="$SUBSCRIPTION_ID"
EOF
  date +%s >"$STAMP"
  log "logged in. Subscription: ${SUBSCRIPTION_ID:-<unset>}. Env written to $ENV_OUT"
  return 0
}

MODE="${1:-auto}"
case "$MODE" in
  --check)  is_fresh && exit 0 || exit 1 ;;
  --force)  do_login; exit $? ;;
  --export)
    is_fresh || do_login >/dev/null 2>&1 || true
    [ -f "$ENV_OUT" ] && . "$ENV_OUT"
    # When sourced, ARM_* are now in the caller's shell.
    ;;
  *)        is_fresh && { log "credentials fresh; skipping login."; exit 0; }; do_login; exit $? ;;
esac
